// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Younghyeon Park
//! Thermal duty — closing [OPEN_RISKS R5](../../docs/OPEN_RISKS.md).
//!
//! ADR-0021 checked the motor **electrically** — 2.79 A peak against a 4.19 A
//! rating, 0.89 A RMS against 1.60 A — and called it comfortable. That is not the
//! thermal question. The thermal question is whether the heat can *leave*, and R5
//! has sat as "gated on hardware" ever since.
//!
//! It is not gated on hardware. A lumped-capacitance model answers it, and the
//! answer changes a design decision.
//!
//! # The finding
//!
//! **The battery is the thermal protection, by coincidence rather than design.**
//! The girdle's time constant (~53 min) is longer than the runtime it can be fed
//! for (~30 min), so the robot runs out of energy before it overheats. Tether it,
//! or hot-swap the pack, and that protection vanishes: continuous trotting with a
//! polished girdle settles near **114 °C**.
//!
//! # ⚠️ What this model does not see
//!
//! - **Winding hotspots.** A lumped mass has ONE temperature. The real winding is
//!   hotter than the skin these numbers describe, and the winding is what fails.
//!   Treat every figure here as an assembly-skin temperature, i.e. optimistic for
//!   the component that actually matters.
//! - **Copper loss only.** Inherited from ADR-0021 — no iron, switching or gearbox
//!   losses, so the real dissipation is higher than the watts fed in here.
//! - **Internal conduction is assumed perfect** at girdle level. The Biot number
//!   says the lumped approximation is safe for a *solid* block; a girdle is a
//!   structure with motors and air gaps inside, so it is weaker than the number
//!   suggests.
//! - The girdle envelope, `h`, emissivities and motor geometry are all `[assumed]`,
//!   which is why every result is swept rather than stated once.

use dualis_core::substance::ThermalProps;
use dualis_core::{Domain, Exchange, Substance};
use dualis_thermal::{Environment, LumpedMass, HEAT};
use dualis_units::{
    Area, Density, Length, Power, SpecificHeat, Temperature, ThermalConductivity,
    ThermalExpansion, Time, Volume,
};

/// Per-motor dissipation and runtimes, generated by `tomcat_kin.power`.
///
/// ⚠️ These are copied from the Python model, so they can go stale. The pytest
/// `tests/test_thermal_constants.py` fails if `power.py` moves away from them —
/// which is the only thing keeping this crate honest.
pub mod from_power_py {
    /// Copper loss per leg motor at the 50 cm/s trot, W. (`copper_w / 12`)
    pub const TROT_W: f64 = 3.5029;
    /// Per-motor draw HOLDING a stance, W. Higher than trotting — a cable can only
    /// pull, so posture costs current. (`legs_w / 12`)
    pub const STAND_W: f64 = 4.3514;
    /// Minutes of trotting on the 300 g pack.
    pub const TROT_RUNTIME_MIN: f64 = 30.16;
    /// Minutes standing on the pack, brake OFF.
    pub const STAND_RUNTIME_MIN: f64 = 37.49;
}

/// Room air. Everything is quoted as a rise, so this only sets the absolute scale.
pub const AMBIENT_C: f64 = 25.0;
/// Still-air convective coefficient, W·m⁻²·K⁻¹. `[assumed]`
pub const STILL_AIR_H: f64 = 7.0;
/// Bare/polished aluminium.
pub const EMIS_POLISHED: f64 = 0.09;
/// Anodised — and the single cheapest thermal lever available here.
pub const EMIS_ANODISED: f64 = 0.90;

/// A body that heats up: geometry, mass and surface finish.
#[derive(Clone, Copy, Debug)]
pub struct Part {
    /// Outer surface available to lose heat through, m².
    pub area_m2: f64,
    /// Enclosed volume, m³.
    pub volume_m3: f64,
    /// Mass, kg.
    pub mass_kg: f64,
    /// Specific heat, J·kg⁻¹·K⁻¹.
    pub cp: f64,
    /// Bulk conductivity, W·m⁻¹·K⁻¹ — only used for the Biot check.
    pub k: f64,
}

impl Part {
    /// One SteadyWin GIM3505-9, free-standing.
    ///
    /// "3505" is a 35 mm stator; with the housing and the 9:1 planetary the external
    /// envelope is about ⌀46 × 33 mm `[assumed]`. `cp = 450` rather than aluminium's
    /// 896 because a motor is copper, electrical steel, magnets and air — and that
    /// choice **halves the time constant**, which is the whole answer here.
    pub fn motor() -> Part {
        let (d, l) = (0.046, 0.033);
        Part {
            area_m2: 2.0 * std::f64::consts::PI * d * d / 4.0 + std::f64::consts::PI * d * l,
            volume_m3: std::f64::consts::PI * d * d / 4.0 * l,
            mass_kg: 0.1317,
            cp: 450.0,
            k: 50.0,
        }
    }

    /// The front girdle: six motors and the structure holding them.
    ///
    /// **This is the honest boundary.** P1 centralises the motors, so their
    /// individual surfaces are not free to room air — the assembly skin is what
    /// rejects the heat, and it cannot reject more than its own area allows however
    /// good the internal conduction is.
    pub fn girdle() -> Part {
        let (w, h, d) = (0.096, 0.060, 0.060); // spans the ±48 mm track `[assumed]`
        Part {
            area_m2: 2.0 * (w * h + w * d + h * d),
            volume_m3: w * h * d,
            mass_kg: 1.122, // params.front_girdle_mass — motors included
            cp: 600.0,
            k: 150.0,
        }
    }

    fn substance(&self, emissivity: f64) -> Substance {
        Substance {
            name: "part".to_string(),
            density: Density::kg_per_m3(self.mass_kg / self.volume_m3),
            thermal: Some(ThermalProps {
                conductivity: ThermalConductivity::w_per_m_k(self.k),
                specific_heat: SpecificHeat::j_per_kg_k(self.cp),
                expansion: ThermalExpansion::ppm_per_k(23.0),
                emissivity,
            }),
            mechanical: None,
            acoustic: None,
        }
    }

    /// Build the lumped domain for this part.
    pub fn lumped(&self, emissivity: f64, h: f64) -> LumpedMass {
        LumpedMass::new(
            "part",
            self.substance(emissivity),
            Volume::from_si(self.volume_m3),
            Length::from_si(self.volume_m3 / self.area_m2),
            Temperature::celsius(AMBIENT_C),
            Environment {
                ambient: Temperature::celsius(AMBIENT_C),
                convection_w_per_m2_k: h,
                area: Area::from_si(self.area_m2),
            },
        )
    }

    /// Rise above ambient (K) after `minutes` absorbing `watts`.
    ///
    /// Stepped rather than solved, so the radiative `εσA(T⁴-Tₐ⁴)` term is carried
    /// exactly instead of linearised — it is the same order as still-air convection
    /// at these temperatures, so linearising it would hide the anodising result.
    pub fn rise_after(&self, emissivity: f64, h: f64, watts: f64, minutes: f64) -> f64 {
        let mut m = self.lumped(emissivity, h);
        let mut bus = Exchange::new();
        let dt = 1.0;
        for k in 0..(minutes * 60.0 / dt) as usize {
            bus.publish(HEAT, watts * dt);
            m.step(Time::s(k as f64 * dt), Time::s(dt), &mut bus)
                .expect("lumped step");
        }
        m.rise().to_si()
    }

    /// Settled rise (K) — 10 time constants is plenty.
    pub fn equilibrium(&self, emissivity: f64, h: f64, watts: f64) -> f64 {
        let tau = self.time_constant_min(h);
        self.rise_after(emissivity, h, watts, tau * 10.0)
    }

    /// `C/(hA)` in minutes.
    pub fn time_constant_min(&self, h: f64) -> f64 {
        self.lumped(EMIS_POLISHED, h).time_constant().to_si() / 60.0
    }

    /// `hL/k` — whether one temperature was an honest description.
    pub fn biot(&self, h: f64) -> f64 {
        self.lumped(EMIS_POLISHED, h).biot_number()
    }

    /// Convection-only steady rise, `P/(hA)`.
    pub fn equilibrium_no_radiation(&self, h: f64, watts: f64) -> f64 {
        self.lumped(EMIS_POLISHED, h)
            .equilibrium_rise(Power::w(watts))
            .to_si()
    }
}

#[cfg(test)]
mod tests {
    use super::from_power_py::*;
    use super::*;

    #[test]
    fn lumped_approximation_is_honest_for_both_parts() {
        // Under ~0.1 the body has no internal gradient this model cannot see.
        assert!(Part::motor().biot(STILL_AIR_H) < 0.1);
        assert!(Part::girdle().biot(STILL_AIR_H) < 0.1);
    }

    #[test]
    fn centralising_the_motors_costs_rejection_area() {
        // P1's first measured THERMAL cost: the girdle skin is smaller than the six
        // motor surfaces it swallows. Everywhere else P1 has paid off.
        let six_motors = 6.0 * Part::motor().area_m2;
        let girdle = Part::girdle().area_m2;
        assert!(girdle < six_motors);
        let lost = 1.0 - girdle / six_motors;
        assert!((0.30..0.45).contains(&lost), "area lost was {lost}");
    }

    #[test]
    fn the_battery_outlasts_nothing_the_girdle_outlasts_the_battery() {
        // The protection is the girdle's thermal mass, not any deliberate margin:
        // tau must exceed the runtime it can be fed for, or it reaches equilibrium.
        assert!(Part::girdle().time_constant_min(STILL_AIR_H) > TROT_RUNTIME_MIN);
    }

    #[test]
    fn continuous_trot_on_a_polished_girdle_is_too_hot() {
        // The result that stops R5 being "comfortable": remove the battery limit
        // and a bare girdle settles past 100 C.
        let rise = Part::girdle().equilibrium(EMIS_POLISHED, STILL_AIR_H, 6.0 * TROT_W);
        assert!(AMBIENT_C + rise > 100.0, "settled at {} C", AMBIENT_C + rise);
    }

    #[test]
    fn anodising_is_worth_more_than_thirty_kelvin() {
        // Radiation is the same order as still-air convection here, so emissivity
        // 0.09 -> 0.90 is the cheapest lever available.
        let g = Part::girdle();
        let polished = g.equilibrium(EMIS_POLISHED, STILL_AIR_H, 6.0 * TROT_W);
        let anodised = g.equilibrium(EMIS_ANODISED, STILL_AIR_H, 6.0 * TROT_W);
        assert!(polished - anodised > 30.0, "gain was {}", polished - anodised);
        assert!(AMBIENT_C + anodised < 80.0);
    }

    #[test]
    fn standing_without_the_brake_is_the_worst_thermal_case() {
        // Reinforces ADR-0021 from a direction it never checked: a cable can only
        // pull, so holding a stance draws MORE per motor than trotting does.
        assert!(STAND_W > TROT_W);
        let g = Part::girdle();
        assert!(
            g.equilibrium(EMIS_POLISHED, STILL_AIR_H, 6.0 * STAND_W)
                > g.equilibrium(EMIS_POLISHED, STILL_AIR_H, 6.0 * TROT_W)
        );
    }

    #[test]
    fn motor_mass_uncertainty_moves_tau_but_not_equilibrium() {
        // OPEN_RISKS R1 is a heat-CAPACITY uncertainty, not a heat-REJECTION one:
        // it changes how fast you get there, never where you end up.
        let light = Part::motor();
        let heavy = Part { mass_kg: 0.200, ..light };
        assert!(heavy.time_constant_min(STILL_AIR_H) > light.time_constant_min(STILL_AIR_H));
        assert!(
            (heavy.equilibrium_no_radiation(STILL_AIR_H, TROT_W)
                - light.equilibrium_no_radiation(STILL_AIR_H, TROT_W))
            .abs()
                < 1e-9
        );
    }
}
